language: node_js
node_js:
  - "8.4"
cache: yarn
script:
  - yarn --version
  - yarn sass
# Commented out because of problems introduced by nyc
#  - yarn check
  - yarn lint
  - yarn test
  - yarn test:routes
  - yarn test:a11y
  - yarn test:nsp
